apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cpp-prog-imagepolicy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cpp-prog-imagerepo
  policy:
    semver:
      range: '>= 1.0.0 <2.0.0'

