---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cpp-prog-git
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/emilk92/cpp_prog
